apiVersion: "aci.ctrl/v1"
kind: AciEpg
metadata:
  name: epgtest
spec:
  tenant: cpaggenk8s
  ap: annotated
  epgName: coolapp
  bd: aci-containers-cpaggenk8s-pod-bd
  contracts:
  - name: default
    relation: consumer
  - name: default
    relation: provider
  - name: aci-containers-cpaggenk8s-dns
    relation: consumer
  - name: aci-containers-cpaggenk8s-istio
    relation: consumer
  - name: aci-containers-cpaggenk8s-icmp
    relation: consumer
  - name: aci-containers-cpaggenk8s-health-check
    relation: provider
  - name: cpaggenk8s-l3out-allow-all
    relation: consumer
